---
title: "Module 2, Assignment 2"
author: "Ellen Bledsoe"     # <- your name here!
date: "`r Sys.Date()`"      # <- uses the current date when rendered
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Student Answer Key

### This document contains the answers to the assignment without the code that produces it.

1.  

```{r messsage = FALSE}
# Load library
library(tidyverse)
```

2.  

```{r}
# Load data
growth <- read_csv("../data/tilapia_growth.csv")

# Head
head(growth)

# Tail
tail(growth)
```

3.  

```{r}
# a)

# b)

# c)

# d)
```

4.  

```{r}
# Task (a):

# Task (b):

# Task (c):

# Task (d):
```

```{r}
# Do as.factor on perc_soy_protein 
growth <- growth %>% 
  mutate(perc_soy_protein = as.factor(perc_soy_protein))
```

5.  

```{r}
# Add a day_30_weight_kg column to data frame
growth <- growth %>%
  mutate(day_30_weight_kg = day_30_weight / 1000)

# View
print.data.frame(head(growth))
```

6.  

```{r}
# Data frame with the average growth per treatment
growth_by_treatment <- growth %>%
  group_by(perc_soy_protein) %>%
  summarize(mean_weight_kg = mean(day_30_weight_kg))

# View
growth_by_treatment
```

7.  

```{r}
# Box plot percent soy protein in the diet v. the weight at 30 days
ggplot(growth, aes(perc_soy_protein, day_30_weight_kg)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  labs(x = "Percent Diet Comprised of Soy Protein",
   y = "Tilapia Weight at 30 Days (kg)") +
  theme_light()
```

8.  

```{r}
# Average growth per treatment (perc_soy_protein) and if tanks are warm or cold
growth_by_treatment_and_temp <- growth %>%
  group_by(perc_soy_protein, tank_category) %>%
  summarise(mean_weight_kg = mean(day_30_weight_kg))

# View
growth_by_treatment_and_temp
```

9.  

```{r}
# Scatterplot average tank temperature v. the weight at 30 days
ggplot(growth, aes(avg_tank_temp, day_30_weight_kg, color = perc_soy_protein)) +
  geom_point() +
  labs(x = "Average Tank Temperature (C)",
   y = "Tilapia Weight at 30 Days (kg)",
   color = "Percent Soy Protein") +
  theme_light()
```

10. 

```{r}
# Answer:
```

11. 

```{r}
# Answer:
```
