---
title: 'Module 1, Assignment 2: Answer Key'
author: "Ellen Bledsoe"     # <- your name here!
date: "`r Sys.Date()`"      # <- uses the current date when rendered
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Student Answer Key

### This document contains the answers to the assignment without the code that produces it.

## Vectors

```{r vector}
# Vector with counts of penguins
counts <- c(2, 9, 4, 3, 6, 7, 1, 0, 3)
```

1.  

```{r data_class}
# Data class for counts
class(counts)
```

2.  

```{r second_value}
# Second value of counts vector
counts[2]
```

3.  

```{r avg_penguins}
# Mean number of penguins
mean(counts)
```

```{r import_data}
# Load library
team_data <- read.csv("../data/team_antarctica_responses.csv")
```

## Data Frames

4.  

```{r examine_data}
# First 10 rows of data
head(team_data, 10)
```

5.  

```{r}
# Parka color for UniqueID 9
team_data[9, 7]
```

6.  

```{r average_remote_location}
# Average rating to live in a remote location
mean(team_data$remote_location)
```

7.  

```{r min_max_distance}
# Minimum distance
min(team_data$distance_mi)

# Maximum distance
max(team_data$distance_mi)
```

8.  

```{r cooking_skill}
# Dataframe with only those with fishing skill rating of 5
team_data[team_data$fishing_skill == 5, ]
```

9.  

```{r good_with_animals}
# Data class of a column
class(team_data$good_with_animals)
```

10. 

```{r parka_colors}
# Average cold tolerance of people with blue parkas
mean(team_data[team_data$parka_color == "Blue", 4])
```

## Bonus (up to 2 points)!

```{r flag_mascot}
# Data frame for flag mascot votes
mascot <- team_data$flag_mascot

# Mascot count
table(mascot)
```

```{r}
# Answer:
```
